version: '3.7'


# container to run tests and other developer activities
services:
  php:
    container_name: data-getter-helper-php
    image: data-getter-helper-php
    build:
      context: php
    volumes:
      - ./../:/var/app:cached
